name: CI
on: [push]
jobs:
  build:
    name: Building and Testing BatakJava
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Build BatakJava
      run: |
        git submodule init
        git submodule update
        mvn install:install-file \
          -Dfile="com.microsoft.z3.jar" \
          -DgroupId="com.microsoft" \
          -DartifactId="z3" \
          -Dversion="4.8.7" \
          -Dpackaging=jar \
          -DgeneratePom=true
        ./gradlew build